config/routes.rb
Rails.application.routes.draw do

  resources :tiers
  get 'signup', :to => 'users#new'
  get 'login', :to => 'sessions#new' 
  get 'logout', :to => 'sessions#destroy'
  get 'edit' => 'users#edit'
  post 'edit'   => 'users#update'
  resources :sessions
  resources :subscriptions, only: [:new, :create, :destroy]
  resources :gyms, only: [:index, :show, :destroy]
  resources :users, only: [:index, :welcome, :show, :new, :create, :destroy, :edit, :update]

  root to: 'gyms#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/gym.rb
class Gym < ApplicationRecord
    has_many :subscriptions, dependent: :destroy
    has_many :users, through: :subscriptions
end

app/models/session.rb
class Session < ApplicationRecord
end

app/models/subscription.rb
class Subscription < ApplicationRecord
    belongs_to :user
    belongs_to :gym
    has_many :tiers

    validates_uniqueness_of :user_id, :scope => :gym_id
end

app/models/tier.rb
class Tier < ApplicationRecord
    belongs_to :subscription
    
end

app/models/user.rb
class User < ApplicationRecord
    has_many :subscriptions, dependent: :destroy
    has_many :gyms, through: :subscriptions

    validates :name, presence: true
    validates :name, uniqueness: true 

    has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :setup_notification_stuff, :setup_auth_stuff
    private
    def current_user
        @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end
    helper_method :current_user
    def setup_notification_stuff
      @errors = flash[:errors]
      @notification = flash[:notification]
    end
    def setup_auth_stuff
      @logged_in = logged_in?
      @logged_in_user = User.find(current_user.id) if logged_in?
    end
    def log_out_user!
      session.delete(:user_id)
    end
    def log_in_user(user_id)
      session[:user_id] = user_id
    end
    def logged_in?
      !!current_user
    end

    def authorize 
      redirect_to login_url, alert: "Not authorized" if current_user.nil?
    end 

end

app/controllers/gyms_controller.rb
class GymsController < ApplicationController

    def index 
        @gyms = Gym.all
    end

    def show 
        @tier = Tier.new
        @tiers = Tier.all
        @gym = Gym.find(params[:id])
        @users = User.all
        @subscription = Subscription.new
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def new 
    end 

    def show 
        @user = User.find(params[:id])
    end
    
    def create 
        user = User.find_by_name(params[:name])
        if user && user.authenticate(params[:password])
            session[:user_id] = user.id
            redirect_to gyms_path, notice: "Logged in!"
        else 
            flash.now.alert = "Email or password is invalid"
            render "new"
        end 
    end 

    def destroy 
        session[:user_id] = nil 
        redirect_to new_session_path
    end
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController

    def new 
        @subscription = Subscription.new
    end 

    def create 
        @subscription = Subscription.create(subscription_params)
        if @subscription.valid?
         redirect_to user_path(@subscription.user)
        else 
            flash[:suberror] = "You're already subscribed to that gym"
            redirect_to user_path(@subscription.user)
        end 
    end 

    def destroy

        @subscription = Subscription.find(params[:id])
        @subscription.destroy
        redirect_to user_path(@subscription.user)
    end

    private 
    
    def subscription_params
        params.require(:subscription).permit(:user_id, :gym_id)
    end
end     

app/controllers/tiers_controller.rb
class TiersController < ApplicationController

    def show 
        @subscription = Subscription.find(params[:id])
    end 

    def new 
        @tier = Tier.new
    end 

    def create 
        @tier = Tier.create(params[:package], params[:subscription_id])
        if @tier.valid?
            redirect_to user_path(@tier.subscription)
        else 
            flash[:suberror] = "You're already subscribed to that gym"
            redirect_to user_path(@subscription.user)
        end 
    end 

    def update 
    end 
    
    def destroy 
    end 

    private 

    def tier_params 
        params.require(:tier).permit(:package, :subscription_id)
    end 
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authorize, only: [:show, :update]

    def index 
    end 
    

    def new 
        @user = User.new    
    end 

   def create
        @user = User.create(user_params)
          if @user.valid?
            session[:user_id] = @user.id
            redirect_to @user, notice: "Thank you for signing up!"
          else 
            flash[:errors] = @user.errors.full_messages
            redirect_to new_user_path
          end
    end 
    
    def show 
        @user = User.find(params[:id])
        @subscription = Subscription.new
        @gyms = Gym.all
    end 

    def edit 
      @user = current_user
    end

    def update 
      @user = current_user
      @user.update_attributes(edit_params)
      redirect_to user_path(@user)
    end 

    private 

    def user_params
        params.require(:user).permit(:name, :password)
    end 

    def subscription_params
      params.require(:subscription).permit(:user_id, :gym_id)
    end

    def edit_params
      params.require(:user).permit(:name)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gyms_helper.rb
module GymsHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tiers_helper.rb
module TiersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/gyms/index.html.erb
<h1>Welcome to House of Gains, bro!</h1>
<br>
<h2>Here are the gyms in your area</h2>

<ol>
    <%  @gyms.each do |gym| %>
        <h3><%= link_to gym.name, gym_path(gym) %></h3>
        <p> </p>
    <% end %>
</ol>

app/views/gyms/show.html.erb
<h1><%= @gym.name %></h1>
<h2>Address: <%= @gym.address %></h2>

    <%= form_for @subscription do |f|%>
    <%= f.hidden_field :user_id, value: @current_user.id %>
    <%= f.hidden_field :gym_id, value: @gym.id %>
    <%= f.submit "Subscribe" %>
    <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Welcome to the House of Gains!</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.8.0/css/bulma.min.css">
    <script defer src="https://use.fontawesome.com/releases/v5.3.1/js/all.js"></script>
  </head>
  <body>
  <section class="section">
    <div class="container">
      <h1 class="title", style="text-align:center;">
        House Of Gains
      </h1>
      <p class="subtitle">
       
      </p>
    </div>
  </section>
  </body>
</html>

<!DOCTYPE html>
<html>
  <head>
    <title>Houseofgains</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
  <% if current_user %>
    Logged in as <%= current_user.name %>.
    <br>
    <%= link_to "Check All Gyms", root_url %>
    <%= link_to "View Profile", user_path(current_user[:id]) %>
    <%= link_to "Edit Profile", edit_user_path(current_user) %>
    <%= link_to "Log out", session_path("current"), method: "delete" %>
    <% else %> 
    <%= link_to "Sign Up", signup_path %>    
    <%= link_to "Log in", login_path %>
    <% end %>
    <br>

    <% flash.each do |name, msg| %>
     <div id='flash'><%= content_tag :div, msg, id: "flash_#{name}" %> </div>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/subscriptions/new.html.erb
<%= form_for @subscription do |f| method: post %>
    <%= f.label :gym_id %>
    <%= f.collection_select :gym_id, Gym.all, :id, :name %>
    <%= f.submit "Subscribe" %>
<% end %>

app/views/users/edit.html.erb
<%= form_for @current_user, action: :update  do |f| %>
    <%= f.text_field :name %>
    <%= f.submit "Update Account" %>
<% end %>

app/views/users/index.html.erb
<h1> Welcome to the House of Gains </h1> 
<%= link_to "Click here to see all the gyms!", gyms_path(@gyms) %>

app/views/users/new.html.erb
<h1> Sign up </h1>

<pre>
<%= form_for @user do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>
    <%= f.label :password %>
    <%= f.password_field :password %>
    <%= f.submit %> 
<% end %>
</pre>

app/views/users/show.html.erb
<br>
<h1>Hello <%= @current_user.name %>!</h1>
<% if flash[:suberror]%>
     <h2 id= "error"><%= flash[:suberror] %></h2>
<%end%>

<% @current_user.subscriptions.each do |subscription| %>    
      You're subscribed to:
      <%= subscription.gym.name %>
      <%= button_to "Unsubscribe", subscription_path(subscription), method: "delete" %>
      <br>
 <%end%>